{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: "distributed-scheduler-ingress"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "distributed-scheduler.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ if $.Values.ingress.annotations }}
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{ range $key, $value := .Values.ingress.hosts }}
    - host: {{ $value.host | quote }}
      http:
        paths:
          {{ range $value.paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{include "distributed-scheduler.fullname" $ }}-manager
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}