{{- define "distributed-scheduler.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Args.Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "distributed-scheduler.labels" . | nindent 4 }}
  {{- with .Args.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Args.Values.servicePort | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "distributed-scheduler.selectorLabels" . | nindent 4 }}
{{- end -}}